"""empty message

Revision ID: f16f720362fe
Revises: 
Create Date: 2020-06-18 23:00:29.820125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16f720362fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subreddit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subreddit', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_embedding', sa.PickleType(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('body_embedding', sa.PickleType(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('subreddit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subreddit'], ['subreddit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread')
    op.drop_table('subreddit')
    # ### end Alembic commands ###
